FROM python:3.12-slim

WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV PIP_NO_CACHE_DIR=1

COPY requirements-api.txt pyproject.toml README.md ./

RUN pip install --upgrade pip \
    && pip install -r requirements-api.txt \
    && pip install --no-deps xgboost

COPY src ./src

EXPOSE 8000

CMD ["uvicorn", "src.serving.api:app", "--host", "0.0.0.0", "--port", "8000"]
